config/routes.rb
Sherlock::Application.routes.draw do
    
  devise_for :users, :controllers => {
    :sessions       => 'sessions',
    :registrations  => 'registrations'
  }
  
  mount RailsAdmin::Engine => '/admin', :as => 'rails_admin'
  
  resources :text_snippets
  resources :letterheads
  resources :logos
  resources :clients
  
  resources :employees
    
  resources :folders
  resources :reports
  
  resources :contact_messages
  
  resources :block_swaps, :only => [ :create ]  
  
  resources :captured_emails
  
  resources :purchases
  
  resources :subscription_plans
  
  resources :events
  
  resources :file_assets
    
  resources :impersonations  
  
  resources :cases do
    resources :html_details
    resources :data_log_details
    resources :witness_statements
    resources :page_breaks
    resources :pictures
    resources :videos
    resources :invitations
    resources :footers
    resources :notes
    resources :viewers
  end
  
  namespace :dashboard do
    resources :users    
    resources :clients
    resources :blocked_ips
    resources :client_conversions, :only => [:new, :create]
  end
  
  scope '/chargify' do
    get  'subscriptions/new'  => 'chargify/subscriptions#new'
    post 'events/create'      => 'chargify/events#create'
  end  
  
  post 'folders/:id/move_case'      => 'folders#move_case'
  post 'folders/:id/move_out_case'  => 'folders#move_out_case'
    
  resource :account, :only => [:show, :update]
 
  get 'search/index'  => 'search#index', :as => :search
  
  get 'account/upgrade' => 'accounts#upgrade', :as => :upgrade
  get 'account/renew' => 'accounts#renew', :as => :renew
  
  get 'cases/preview/:id' => 'cases#preview', :as => :case_preview
  
  match 'spellcheck/lookup' => 'spellcheck#lookup', 
        :as => :spellcheck, :via => [:get, :post]
  
  post  'temp_videos/exists'  => 'temp_videos#exists', :as => :check_temp_video
  put   'temp_videos'         => 'temp_videos#create', :as => :new_temp_video
  
  get 'dashboard' => 'home#dashboard',  :as => :dashboard
  
  get 'pricing'   => 'home#pricing',    :as => :pricing
  get 'help'      => 'home#help',       :as => :help  
  get 'contact'   => 'home#contact',    :as => :contact
  get 'tos'       => 'home#tos',        :as => :tos
  get 'privacy'   => 'home#privacy',    :as => :privacy
  get 'how_it_works' => 'home#how_it_works', :as => :how_it_works
  
  resources :blocks
  
  get 'logo/:filename' => 'files#logo',
    :constraints => { :filename => /.*/ }, :as => :logo
  
  get 'files/:case_id/:type/:filename' => 'files#show',
    :constraints => { :filename => /.*/ }, :as => :file
  
  get 'video_thumbnails/:case_id/:filename' => 'files#video_thumbnail',
    :constraints => { :filename => /.*/ }, :as => :file_video_thumbnail
  

  root :to => 'home#index'

end

app/models/note.rb
class Note < ActiveRecord::Base
  
  belongs_to :case
  
  attr_accessible :contents
  
end

app/controllers/notes_controller.rb
class NotesController < ApplicationController
  
  before_filter :authenticate_user!
  before_filter :authorize_pi!
  
  before_filter :resolve_case
  before_filter :resolve_note, :except => [ :new, :create ]
  
  # GET /notes
  # GET /notes.json
  
  def index
    @notes = @case.notes.order('id DESC')
  
    respond_to do |format|
      format.html # index.html.erb
      format.json { render :json => @notes }
    end
  end

  # GET /notes/1
  # GET /notes/1.json
  def show    
    respond_to do |format|
      format.html # show.html.erb
      format.json { render :json => @note }
    end
  end

  # GET /notes/new
  # GET /notes/new.json
  def new    
    @note = @case.notes.new
    respond_to do |format|
      format.html
      format.js
      format.json { render :json => @note }
    end
  end

  # GET /notes/1/edit
  def edit
    respond_to do |format|
      format.js
    end
  end

  # POST /notes
  # POST /notes.json
  def create
    
    @note = @case.notes.new params[:note]
    
    respond_to do |format|
      if @note.save
        
        KM.identify current_user.id
        KM.record('created note', :case_id => @case.id)
        
        @notes_count = @note.case.notes.count
        
        format.html do 
          redirect_to edit_case_note_path(@case, @note), 
                      :notice => 'Note was successfully created.'                    
        end
        format.js
        format.json { render :json => @note, :status => :created, :location => @note }
      else
        format.html { render "new" }
        format.json { render :json => @note.errors, :status => :unprocessable_entity }
      end
    end
  end

  # PUT /notes/1
  # PUT /notes/1.json
  def update
    
    respond_to do |format|
      if @note.update_attributes(params[:note])
        
        format.js
        format.html { redirect_to(
                      edit_case_note_path(@case, @note),
                      :notice => 'Note was successfully updated.') }
        format.json { head :ok }
      else
        
        format.js
        format.html { render "edit" }
        format.json { render :json => @note.errors, :status => :unprocessable_entity }
      end
    end
  end

  # DELETE /notes/1
  # DELETE /notes/1.json
  def destroy
    
    @note.destroy

    respond_to do |format|
      
      @notes_count = @note.case.notes.count
      
      format.html { redirect_to notes_url }
      format.js
      format.json { head :ok }
    end
  end
  
  private
  
  def resolve_case
    resolve_case_using_param(:case_id)
  end
  
  def resolve_note
    @note = @case.notes.find_by_id params[:id]
  end    
  
end

app/views/notes/_dialog.html.haml
#dialog-note-add{:title => 'Create New Note', :style => 'display:none;'}
  .dialog-contents
  

app/views/notes/_edit_link.html.haml
=link_to 'Edit note', edit_case_note_path(@case, note),
 :title => 'Edit this note',
 :class => 'icon icon-pencil',
 :remote => true

app/views/notes/_form.html.haml
=form_for [@case, @note], :remote => true do |f|
  .field
    -unless inline
      =f.label :contents, 'Note Contents', :class => 'inline'
    .contents.note-contents
      =f.text_area :contents, :class => 'rich'
  
  -unless inline
    .actions.no-margin
      =f.submit 'Save', :class => :button
      =link_to 'Cancel', case_notes_path(@case), :class => :cancel

app/views/notes/_none.html.haml
#message-no-notes
  You haven't created any notes yet.

app/views/notes/_note_item.html.haml
%li{ :id => "note-#{note.id}" }
  =render 'notes/edit_link', :note => note
  =render 'notes/remove_link', :note => note
  %span.date
    =format_date note.created_at  
  .note-contents
    =note.contents.html_safe
      

app/views/notes/_remove_link.html.haml
=link_to 'Remove', case_note_path(note.case, note), 
         :class => 'icon icon-trash',
         :title => 'Remove this note',
         :method => :delete, :remote => true, 
         :confirm => 'Are you sure you want to remove this note?'

app/views/notes/create.js.erb
$('span.notes-count').html(<%= @notes_count %>);
$('#message-no-notes').remove();
<% if @notes_count == 1 %>
  $('.notes-list-wrapper').append($('<ul class="notes"/>'));  
<% end %>
var note = '<%= escape_javascript render 'note_item', :note => @note %>';
$('ul.notes').prepend(note);

var added = $('ul.notes li:first');
added.animateHighlight();

SHERLOCK.notes.hideCreateForm();
SHERLOCK.utils.hideAjaxLoading();

SHERLOCK.utils.linkAjaxify(added.find('a.icon-pencil'));

app/views/notes/destroy.js.erb
$('span.notes-count').html(<%= @notes_count %>);
<% if @notes_count == 0 %>
  $('.notes-see-all').remove();
  $('ul.notes').remove();
  var message = '<%= escape_javascript render 'notes/none' %>';
  $('.notes-list-wrapper').append(message);  
<% end %>
$('.notes li#note-<%= @note.id %>').remove();

app/views/notes/edit.js.erb
tinyMCE.execCommand('mceRemoveControl', false, 'note_contents');
var quickAddDialog = $('#dialog-note-add');
quickAddDialog.dialog('option', 'title', 'Edit Note');
$('.dialog-contents', quickAddDialog).html(
  '<%= escape_javascript(render 'form', :inline => true) %>'
);
quickAddDialog.dialog('open');
tinyMCE.execCommand('mceAddControl', false, 'note_contents');

SHERLOCK.utils.hideAjaxLoading();
SHERLOCK.utils.formAjaxify($('.edit_note'));

app/views/notes/index.html.haml
.breadcrumb
  =link_to 'Dashboard', dashboard_path
  \/
  =link_to 'My Cases', cases_path
  \/
  =link_to @case.title, @case
  \/
  Notes

%h1 Case Notes

.notes-list-wrapper
  - if @notes.empty?
    =render 'none'    
  - else
    =link_to 'Create Note', new_case_note_path(@case), :remote => true
    %ul.notes
      -@notes.each do |note|
        =render 'note_item', :note => note        

%div{:id => 'create-note-wrapper'}
  =link_to 'Create Note', new_case_note_path(@case), :remote => true

=render 'shared/tinymce'
=render 'notes/dialog'

:javascript
  $(function() { SHERLOCK.notes.init(); });

app/views/notes/new.html.haml
=render 'form'

=render 'shared/tinymce'
:javascript
  $(function() {    
    SHERLOCK.notes.init();    
  });

app/views/notes/new.js.erb
tinyMCE.execCommand('mceRemoveControl', false, 'note_contents');
var quickAddDialog = $('#dialog-note-add');
if (quickAddDialog.length) {  
  quickAddDialog.dialog('option', 'title', 'Create New Note');
  $('.dialog-contents', quickAddDialog).html(
  '<%= escape_javascript(render 'form', :inline => true) %>'
  );
  quickAddDialog.dialog('open');
  tinyMCE.execCommand('mceAddControl', false, 'note_contents');
} else {
  $('#create-note-wrapper').after('<%= escape_javascript(render 'form', :inline => false) %>');
  $('#create-note-wrapper').hide();
  tinyMCE.execCommand('mceAddControl', false, 'note_contents');
}
SHERLOCK.utils.hideAjaxLoading();
SHERLOCK.utils.formAjaxify($('#new_note'));

app/views/notes/update.js.erb
SHERLOCK.utils.hideAjaxLoading();
var item = $('#note-<%= @note.id %>');
var contents = item.find('.note-contents');
contents.html('<%= escape_javascript @note.contents.html_safe %>');

item.animateHighlight();