config/routes.rb
Sherlock::Application.routes.draw do
    
  devise_for :users, :controllers => {
    :sessions       => 'sessions',
    :registrations  => 'registrations'
  }
  
  mount RailsAdmin::Engine => '/admin', :as => 'rails_admin'
  
  resources :text_snippets
  resources :letterheads
  resources :logos
  resources :clients
  
  resources :employees
    
  resources :folders
  resources :reports
  
  resources :contact_messages
  
  resources :block_swaps, :only => [ :create ]  
  
  resources :captured_emails
  
  resources :purchases
  
  resources :subscription_plans
  
  resources :events
  
  resources :file_assets
    
  resources :impersonations  
  
  resources :cases do
    resources :html_details
    resources :data_log_details
    resources :witness_statements
    resources :page_breaks
    resources :pictures
    resources :videos
    resources :invitations
    resources :footers
    resources :notes
    resources :viewers
  end
  
  namespace :dashboard do
    resources :users    
    resources :clients
    resources :blocked_ips
    resources :client_conversions, :only => [:new, :create]
  end
  
  scope '/chargify' do
    get  'subscriptions/new'  => 'chargify/subscriptions#new'
    post 'events/create'      => 'chargify/events#create'
  end  
  
  post 'folders/:id/move_case'      => 'folders#move_case'
  post 'folders/:id/move_out_case'  => 'folders#move_out_case'
    
  resource :account, :only => [:show, :update]
 
  get 'search/index'  => 'search#index', :as => :search
  
  get 'account/upgrade' => 'accounts#upgrade', :as => :upgrade
  get 'account/renew' => 'accounts#renew', :as => :renew
  
  get 'cases/preview/:id' => 'cases#preview', :as => :case_preview
  
  match 'spellcheck/lookup' => 'spellcheck#lookup', 
        :as => :spellcheck, :via => [:get, :post]
  
  post  'temp_videos/exists'  => 'temp_videos#exists', :as => :check_temp_video
  put   'temp_videos'         => 'temp_videos#create', :as => :new_temp_video
  
  get 'dashboard' => 'home#dashboard',  :as => :dashboard
  
  get 'pricing'   => 'home#pricing',    :as => :pricing
  get 'help'      => 'home#help',       :as => :help  
  get 'contact'   => 'home#contact',    :as => :contact
  get 'tos'       => 'home#tos',        :as => :tos
  get 'privacy'   => 'home#privacy',    :as => :privacy
  get 'how_it_works' => 'home#how_it_works', :as => :how_it_works
  
  resources :blocks
  
  get 'logo/:filename' => 'files#logo',
    :constraints => { :filename => /.*/ }, :as => :logo
  
  get 'files/:case_id/:type/:filename' => 'files#show',
    :constraints => { :filename => /.*/ }, :as => :file
  
  get 'video_thumbnails/:case_id/:filename' => 'files#video_thumbnail',
    :constraints => { :filename => /.*/ }, :as => :file_video_thumbnail
  

  root :to => 'home#index'

end

app/models/video.rb
require 'digest/md5'
require 'zip/zip'

class Video < ActiveRecord::Base
  
  CONTENT_TYPES = {      
    '3gp'.to_sym  => 'video/3gpp',
    :mpg          => 'video/mpeg',
    :flv          => 'video/x-flv',
    :mov          => 'video/quicktime'
  }
  
  include FileAssetUtils
  include BlockDetail
  
  belongs_to :block
  belongs_to :storage
  
  has_many :file_assets, :foreign_key => 'parent_id', 
           :conditions => "parent_type = 'videos'", 
           :dependent => :destroy  
  
  attr_accessor :uploaded_file
  attr_accessor :uploaded_thumbnail
  
  attr_accessor :capture_start, :capture_end
  attr_accessor :thumbnail_content_type
    
  validate :require_upload_for_a_new_video, :unless => :persisted?  
  
  before_save :process_upload, :if => :has_uploaded_file?
  before_save :process_thumbnail_upload, :if => :has_uploaded_thumbnail?
  
  after_save :generate_file_assets, :if => :has_uploaded_file?
  
  after_save :invalidate_report
  
  # important: after_update not after_save
  after_update :check_for_thumbnail_pos_change
  
  before_destroy :delete_files
  before_destroy :delete_thumbnail
  
  def self.generate(block)
    Video.new(
      :block          => block,
      :unique_code    => generate_unique_code,
      :thumbnail_pos  => '00:00:01'
    )
  end
    
  def ffmpeg_path
    '/usr/local/bin/ffmpeg'
  end
  
  def file_type
    'videos'
  end
  
  def check_if_3gpp
    self.path.to_s.downcase.end_with? '.3gp'
  end
    
  def thumbnail_method
    self.thumbnail_pos.blank? ? :manual : :auto
  end
  
  def width_for_display(max_width)    
    width > max_width ? max_width : width
  end  
  
  def online_dims
    max_width = Report::MAX_PAGE_WIDTH
    min_width = 450
    result = Picture.scale_to_bounds([width, height], [max_width, 0])
    ratio = (0.0 + result[1]) / result[0]
    if result[0] < min_width
      result[0] = min_width
      result[1] = (ratio * result[0]).round
    end
    result
  end
  
  def extract_thumbnail_from_zip    
    self.thumbnail = path.sub(/([^.]+)$/, 'jpg')
    Zip::ZipFile.open(full_filepath) do |zip_file|      
      zip_file.each do |frame|          
        zip_file.extract(frame, full_thumbnail_path)
        break
      end                
    end    
  end
  
  def recreate_thumbnail_file
    #pp self.thumbnail
    #pp full_thumbnail_path
    
    thumb_pos = '00:00:01' if self.thumbnail_pos.blank?
    
    command = "#{ffmpeg_path} -i #{full_filepath} -vframes 1 " +
                " -ss #{thumb_pos} " +
                " -f image2 #{full_thumbnail_path} 2>&1"    
    #pp "Command:"
    #pp command
    
    Rails::logger.debug("Command is: " + command)
    result = `#{command}`
    Rails::logger.debug("Result of the thumbnail command: " + result)
    
  end
  
  def extract_thumbnail_from_movie    
        
    if thumbnail_pos.to_s.present?     
      
      delete_thumbnail_file_asset
      
      self.thumbnail = path.sub(/([^.]+)$/, 'png')
      command = "#{ffmpeg_path} -i #{full_filepath} -vframes 1 " +
                " -ss #{thumbnail_pos} " +
                " -f image2 #{full_thumbnail_path} 2>&1"    
      
      Rails::logger.debug("Command is: " + command)
      result = `#{command}`
      Rails::logger.debug("Result of the thumbnail command: " + result)

      self.thumbnail_content_type = 'image/png'
      
      update_dims_from_thumbnail    
    
    end      
  end
    
  def generate_file_asset_for_thumbnail
    if self.thumbnail.present? && File.exists?(thumbnail_path)
      FileAsset.create(        
        :parent_id    => self.id,
        :parent_type  => file_type,
        :content_type => self.thumbnail_content_type,
        :user_id      => self.author_id,
        :role         => :thumbnail,
        :path         => self.thumbnail,
        :filesize     => File.size(thumbnail_path)
      )  
    end
  end  
  
  def self.content_type_for_format(format)
    CONTENT_TYPES[format]
  end
  
  def format_for_path(path)
    result = nil
    all_possible_formats.each do |format|
      if full_path_for_suffix(format) == path
        result = format
        break
      end
    end
    result
  end
  
  def generate_file_asset_for_original
    if File.exists?(full_filepath)
      FileAsset.create(        
        :parent_id    => self.id,
        :parent_type  => file_type,
        :user_id      => self.author_id,
        :format       => format_for_path(full_filepath),
        :role         => :orig,
        :content_type => self.content_type,
        :path         => self.path,
        :filesize     => File.size(full_filepath)
      )
    end
  end
  
  def generate_file_asset_for_format(format)
    full_path = full_path_for_format(format)
    if File.exists?(full_path)
      exists = self.file_assets.find_by_format(format)
      FileAsset.create(        
        :parent_id    => self.id,
        :parent_type  => file_type,
        :user_id      => self.author_id,
        :format       => format,
        :content_type => Video.content_type_for_format(format),
        :path         => path_for_format(format),
        :filesize     => File.size(full_path)
      ) unless exists
    end
  end
  
  def generate_file_assets
    if self.file_assets.empty?
      generate_file_asset_for_original
      all_possible_formats.each { |fmt| generate_file_asset_for_format fmt }
      generate_file_asset_for_thumbnail
    end
  end
  
  def thumbnail_file_asset
    self.file_assets.find_by_role :thumbnail
  end  
    
  def is_zip?    
    path.end_with? '.zip'    
  end    
  
  def calculate_fps(frames_count, duration_miliseconds)
    (frames_count == 0) ? 15 : sprintf('%.04f', (frames_count * 1000.0) / duration_miliseconds)
  end
  
  def capture_duration
    capture_end.to_i - capture_start.to_i
  end
  
  def extract_frames(frames_dir)    
    ev = Event.create(
      :event_type => 'unzip', 
      :detail_i1  => File.size(full_filepath)
    )                        
    Zip::ZipFile.open(full_filepath) do |zip_file|
      zip_file.each do |f|
        f_path = File.join(frames_dir, f.name)     
        zip_file.extract(f, f_path)        
      end
    end        
    ev.finish
    
  end
     
  #
  # ffmpeg options specific to the video format
  #
  def extra_video_options_for_format(format)
    case format.to_s
    when 'flv'
      '-ar 44100 -qmax 30'
    else
      ''      
    end
  end    
  
  def update_dims_from_thumbnail
    dims = Dimensions.dimensions full_thumbnail_path
    self.width  = dims[0]
    self.height = dims[1]
  end
  
  def save_first_frame_as_thumbnail(frames_dir)    
    
    delete_thumbnail_file_asset
    
    self.thumbnail = self.path.sub(/([^.]+)$/, 'jpg')    
    self.thumbnail_content_type = 'image/jpeg'
    
    first_frame = frame_files(frames_dir).first
    
    Rails::logger.debug "Thumbnail: #{self.thumbnail}"
    
    Rails::logger.debug "First frame is:"
    Rails::logger.debug first_frame
    
    Rails::logger.debug "Copying to #{full_thumbnail_path}"
    
    FileUtils.copy_file(first_frame, full_thumbnail_path)
    update_dims_from_thumbnail
  end
  
  def frame_files(frames_dir)
    Dir["#{frames_dir}/*.jpg"]
  end
    
  def frames_count(frames_dir)            
    frame_files(frames_dir).count
  end
  
  def encode_do(frames_dir, ext)
    
    video_filename = self.path.sub(/([^.]+)$/, ext)        
    video_full_path = File.join base_dir, video_filename
                
    sound_options = encode_mp3_sound frames_dir
    extra_video_options = extra_video_options_for_format ext            
                
    command = "#{ffmpeg_path} -r #{fps} -b 1800 " +
              " -i #{frames_dir}/%06d.jpg #{extra_video_options} " +
              " #{sound_options} -y #{video_full_path} 2>&1"
            
    Rails::logger.debug("Command: #{command}")    
    ev = Event.create(:event_type => 'video_encode_frames')
    result = `#{command}`
    ev.finish
    
    Rails::logger.debug("Result of the command: " + result)            
    video_filename
    
  end
  
  #
  # Encode the video from a .zip containing video frames (as JPEG images)
  # and optional sound file in AIFF format.
  # 
  # For some reason encoding to mov produces the best results. We recode
  # to other formats (mpg, flv) in the post-processing step. Also tests
  # shown that it's not possible to encode .mpg with frame rates smaller
  # than 19-20; but it's possible to RECODE to mpg from, say, mov where
  # frame rate is 15-16. 
  #
  # Side effects:
  # 
  # - set content_type
  # - set path
  # - set fps
  # - set (and overwrite) thumbnail
  #
  def encode_from_zip
    
    Rails::logger.debug 'Encoding from zip'
    
    full_zip_path = full_filepath    
    frames_dir = full_filepath + '_frames'    
    FileUtils.mkdir frames_dir    
    extract_frames frames_dir    
    self.fps = calculate_fps(frames_count(frames_dir), capture_duration)                    
    self.content_type = 'video/quicktime'
    ext = 'mov'    
    self.path = encode_do(frames_dir, ext)            
    save_first_frame_as_thumbnail frames_dir        
    # remove the zip & frame images (whole dir)
    File.unlink full_zip_path
    FileUtils.rm_rf frames_dir    
  end
  
  #
  # Encode the .AIFF sound file into MP3 (if it exists in the target directory)
  # 
  # Return: options for ffmpeg for embedding the result sound file
  #
  def encode_mp3_sound(frames_dir)    
    src_file = "#{frames_dir}/sound.aiff"
    if File.exists? src_file
      ev = Event.create(:event_type => 'convert_aiff')      
      command = "#{ffmpeg_path} -i #{src_file} -f mp3 -acodec libmp3lame " +
                " -ab 192000 -ar 44100 #{frames_dir}/sound.mp3 2>&1"
      result = `#{command}`
      Rails::logger.debug result
      ev.finish
      "-i #{frames_dir}/sound.mp3 -acodec copy"
    else
      ""
    end      
  end      
      
  def self.populate_missing_codes
    Video.where(:unique_code => nil).each do |video|
      video.unique_code = Video.generate_unique_code

app/controllers/videos_controller.rb
class VideosController < ApplicationController

  before_filter :authenticate_user!
  before_filter :authorize_pi!

  #
  # Note: we may want to remove it, if this controller will also be
  #       used to upload videos unlinked with any blocks/cases
  #
  before_filter :resolve_case, :only => [ :new, :edit, :show, :update, :create ]
  before_filter :verify_case_author!, :only => [ :new, :edit, :update, :create ]
  def new

    block = Block.new
    block.case = @case
    @video  = Video.generate(block)
    @insert_before_id = params[:insert_before_id].to_i
    @cookie = cookies['_sherlock_session']
  end

  def create

    params[:upload] ||= {}

    params[:upload].delete('thumbnail') if params[:video][:thumbnail_method] == 'auto'
    params[:video].delete(:thumbnail_method)

    params[:upload]['video'] =
    TempVideo.get_upload_for_user(self.current_company) if uploaded_via_tmp?

    video     = params[:upload]['video']
    thumbnail = params[:upload]['thumbnail']

    params[:video][:uploaded_file] = video if video
    params[:video][:uploaded_thumbnail] = thumbnail if thumbnail

    @video = Video.new(params[:video])
    @video.block = Block.new(
    :case             => @case,
    :insert_before_id => params[:insert_before_id].to_i
    )

    respond_to do |format|
      if (@video.save)
        TempVideo.remove_for_user(current_company) if uploaded_via_tmp?
        format.html { redirect_to(@case, :notice => 'Video block has been added') }
      else
        format.html { render :action => 'new' }
      end
    end

  end

  #
  # Uploadify makes this strange call to /cases/<case_id>/videos/false - not
  # sure why
  #
  def show
    video_id = params[:id]
    @video = video_id.to_s == 'false' ? nil : @case.videos.find_by_unique_code(video_id)

    respond_to do |format|
      format.html { render :text => 'json call expected' }
      format.js { render :json => @video }
    end
  end

  def edit
    @insert_before_id = 0

    @video = @case.videos.find_by_id(params[:id])

    @cookie = cookies['_sherlock_session']
    redirect_to cases_path unless @video
  end

  def update

    @video = @case.videos.find_by_id(params[:id])
    redirect_to cases_path unless @video

    if uploaded_via_tmp?
      params[:upload] ||= {}
      params[:upload]['video'] = TempVideo.get_upload_for_user(self.current_company)
    end

    has_upload = params[:upload]
    method_auto = params[:video][:thumbnail_method].to_s == 'auto'

    params[:upload].delete :thumbnail if has_upload && method_auto
    if params[:keep_thumbnail].to_i == 1
      params[:video].delete :thumbnail_pos
      params[:upload].delete :thumbnail if has_upload
    end
    params[:video].delete :thumbnail_pos unless method_auto
    params[:video].delete :thumbnail_method

    if has_upload
      video     = params[:upload]['video']
      thumbnail = params[:upload]['thumbnail']
      params[:video][:uploaded_file] = video if video
      params[:video][:uploaded_thumbnail] = thumbnail if thumbnail
    end

    respond_to do |format|
      if @video.update_attributes(params[:video])
        TempVideo.remove_for_user(current_company) if uploaded_via_tmp?
        format.html { redirect_to(@case, :notice => 'The video has been successfully updated') }
      else
        format.html do
          flash[:alert] = 'The video could not be updated'
          render :action => 'edit'
        end
      end
    end

  end

  private

  def uploaded_via_tmp?
    params[:via_tmp].to_i == 1
  end

  def resolve_case
    resolve_case_using_param(:case_id)
  end

  def verify_case_author!
    is_author = (@case.author == current_company)
    redirect_to @case unless is_author
  end

end

app/helpers/video_helper.rb
module VideoHelper

  def file_video_path(video, path = video.path)
    file_path(video.block.case_id, 'videos', path)
  end
  
  def video_thumbnail_path(video)    
    asset = video.thumbnail_file_asset
    file_video_thumbnail_path(video.block.case_id, asset.path)
  end
  
  def thumbnail_pos(video)
    video.thumbnail_pos || '00:00:01'
  end
  
  def video_alignment_options
    [
      ['None', nil],
      ['Left', 'left'],
      ['Right', 'right'],
      ['Center', 'center']
    ]
  end
  
  def video_scaling_options
    [
      ['None', nil],
      ['50%', '50']      
    ]
  end
  
  def video_dynamic_style(video)
        
    online_width = video.online_dims[0]
    style = "width:#{online_width}px;"
    is_narrow_elt = online_width <= Report::NARROW_ELT_WIDTH
      
    case video.alignment
    when 'left'
      if is_narrow_elt
        style += 'float:left;margin:0 1em 1em 0'        
      else
        style += 'clear:both'
      end
    when 'right'
      if is_narrow_elt
        style += 'float:right;margin:0 0em 1em 1em'
      else
        style += 'clear:both'        
      end
    when 'center'
      style += 'margin:auto;clear:both;margin-top:1em;'
    else
      style += 'clear:both;margin-top:1em;'
    end
  end
  
end

app/views/videos/_applet_container.html.erb
<div id="appletContainer" style="display:none;height:60px;"></div>

<script type="text/javascript">
              
    $(function() {            
      
      function normalizeDate(s)
      {
        s = ('' + s).replace(/[^0-9]/g, '');
        return s;
      }
      
      var video_path = '<%= file_video_path(@video, 'DUMMY') %>';      
      
      var video_id = <%= @video.id.to_i %>;
      var url_base_redirect = '<%= case_videos_path(@case) %>';
      var url_check = '<%= case_video_path(@case, @video.unique_code, :js) %>';
      var updated_at = normalizeDate('<%= @video.updated_at %>');
      var settings = {
        cache: false,
        dataType: 'json',
        success: function(data) {
          if (data && (normalizeDate(data.updated_at) != updated_at)) {
            
            if (video_id) {
              video_path = video_path.replace(/DUMMY$/, data.path);
            } else {              
            }
            var url_redirect = url_base_redirect + '/' + data.id + '/edit';
            location.href = url_redirect;            
          } else {
            setTimeout(checkVideo, 2000);
          }
        }
      };
      
      function checkVideo()
      {
        $.ajax(url_check, settings);
      }
      
      $('#btn-screen-capture').click(function() {           
        
        if (!SHERLOCK.utils.startJavaDetectionForCapture()) {
          return;
        } 
        
        $('#java-applet-launching .app-is-running').hide();
        $('#java-applet-launching').show();
        $('#java-applet-launching .please-wait').show();
        $('#java-applet-launching .spinning').show();
        
        var container = $('#appletContainer');
        container.empty();
        {
          <% if @video.id %>
          var post_url = '<%= case_video_url(@case, @video) %>';
          <% else %>
          var post_url = '<%= case_videos_url(@case) %>';
          <% end %>
          var token = $('meta[name=csrf-token]').attr('content');
          var code = '<applet archive="<%= root_url %>SherlockScreen.jar?v=' + new Date().valueOf() + '" ' +
            'code="sherlockscreen.SherlockScreen.class" ' +
            'width="1" height="1" MAYSCRIPT>' +        
            '<param name="type" value="video"/>' +
            '<param name="token" value="' + token + '"/>' +
            '<param name="unique_code" value="<%= @video.unique_code %>"/>' +
            '<param name="cookie" value="<%= @cookie %>"/>' +            
            '<param name="insert_before_id" value="<%= @insert_before_id %>"/>' +
            '<param name="post_url" value="' + post_url + '"/>'+            
            '<param name="editor_url" value="<%= root_url %>SherlockEditor.jar"/>'+            
            '<param name="video_id" value="<%= @video.id.to_i %>"/>' +
            '</applet>';      
          container.html(code);        
          container.show();
          
          checkVideo();
          
         }
      });      
    });        
</script>

app/views/videos/_form.html.erb
<div id="video-form">

<%= render 'shared/form_errors', :errors => @video.errors %>

<%= form_for([@case, @video], 
    :html => { :enctype => 'multipart/form-data' }) do |f| %>

<input type="hidden" name="insert_before_id" value="<%= @insert_before_id %>"/>

<input type="hidden" name="via_tmp" value="0"/>

<div class="field">      
  <%= f.label :title, 'Title :' %>
  <div class="boxfield">
    <%= f.text_field :title, :class => 'txtfield txtfield-wide', :size => 100 %>
  </div>  
</div>

<div class="field">
  <%= f.label :alignment, 'Alignment :' %>
  <div class="rich-dropdown-wrapper rich-dropdown-wrapper-x">
    <%= f.select :alignment, video_alignment_options %>
  </div>
</div>

<div class="field">
  <%= f.label :scaling, 'Scaling (report) :' %>  
  <div class="rich-dropdown-wrapper rich-dropdown-wrapper-x">
    <%= f.select :scaling, video_scaling_options %>
  </div>
</div>

<%= f.hidden_field :unique_code unless @video.id %>

<% if @video.id %>

  <h4 class="label">Video :</h4>

  <div class="field-right">

    <div style="margin-top:1em;">
      <%= render 'videos/jplayer', :video => @video %>
    </div>

    <div style="margin:1em 0;" id="video-change-block">
      <input type="button" 
             class="button button-wide"
             id="btn-video-change" value="Change the Video"/>
      <a href="#" style="visibility:hidden;">Keep the existing video</a>
    </div>
  
  </div> 

  <div id="video-field-wrapper" style="display:none;">      
      
    
<% end %>

  <div class="field">
    
    <div style="padding-top: 10px;margin-left: 130px;margin-bottom:10px;">
      
      <strong style="color:#dd0000;">NOTE:</strong> 
      uploading files over 50MB may take long time to upload - 
      consider recording a screencast.
    </div>    
    
    <label for="upload_video">Select Video :</label>
    
    <% if false %>
    <span class="btn2 fileinput-button">
      <%= file_field 'upload', 'video', 
          :title => 'Select video file to be uploaded' %>                      
          <span>Browse...</span>
    </span>
    <% end %>
    
    <div style="float:left;margin-right: 1em;">
      <%= file_field 'upload', 'video', :title => 'Select video file to be uploaded' %>      
    </div>
    
    <div style="float:left;">
    
      <strong>OR&nbsp;&nbsp;</strong>
      <button id="btn-screen-capture"
              style="padding-left:10px;"
              type="button" class="button2 button2-wide">
          <div>
            Record Screencast
          </div>
      </button>
    
    </div>
    
  </div>
        
  <%= render 'shared/java_detect', 
      :func_name => 'video capture', :app_name => 'Recorder' %>
    
  <% if @video.id %>
</div>

<% end %>

<h4 class="label">Thumbnail :</h4>
<div class="field-right">  
  <% if @video.thumbnail %>  
    <img src="<%= video_thumbnail_path(@video) %>"
         width="<%= @video.online_dims[0] %>"
         /> 
  <% end %>  
</div>

<% if @video.id %>
  
  <input type="hidden" name="keep_thumbnail" value="1"/>
  
  <div class="field-right" style="margin:5px 0;">
    <% if @video.thumbnail_method == :auto %>
    Thumbnail extracted from video, position <strong><%= @video.thumbnail_pos %>.</strong>
    <% else %>
    You have manually uploaded this thumbnail.
    <% end %>
    
    <div style="margin:5px 0;">
      <input type="button" 
             class="button button-wide"
             value="Change Thumbnail"
             id="btn-thumbnail-change"/>
      <span class="hidden">
        <a href="#" id="link-thumbnail-keep">Keep the current thumbnail</a>
      </span>
    </div>
    
  </div>
  <div id="block-thumbnail-change-wrapper"        
       style="display:none;">
<% end %>  
  
<div class="field-right">    
    
  <div id="block-thumbnail-method-auto">
    <%= f.radio_button :thumbnail_method, :auto %>
    <%= f.label :thumbnail_method_auto, 
        'generate automatically from clip', :class => :inline %>
    <span
      <% if @video.thumbnail_method == :manual %>
      class="hidden"
      <% end %>
      >
    - timecode    
    <input type="text" id="video_thumbnail_pos" 
           name="video[thumbnail_pos]" size="10" 
           value="<%= thumbnail_pos(f.object) %>"/>        
    (HH:MM:SS.xxx)
    </span>
  </div>
  <div id="block-thumbnail-method-manual">
    <%= f.radio_button :thumbnail_method, :manual %>
    <%= f.label :thumbnail_method_manual, 
        'manually upload a thumbnail image', :class => :inline %>
    <div
      <% if @video.thumbnail_method == :auto %>
      class="hidden"
      <% end %>
      >
      <label for="upload_thumbnail">Select Thumbnail</label>
      <%= file_field 'upload', 'thumbnail' %>

    </div>
  </div>
    
</div>
    
<% if @video.id %>
  </div>
<% end %>

<div class="actions">
  <%= f.submit 'Save', :class => :button %>  
  <%= link_to 'Cancel', @case %>  
</div>

<% end %>

</div>
  
<script type="text/javascript">    
  var settings = {
    video_id: '<%= @video.id.to_i %>',
    token: '<%= form_authenticity_token %>',
    cookie: '<%= @cookie %>',
    paths: {
      tmp_new:    '<%= new_temp_video_path %>',
      tmp_check:  '<%= check_temp_video_path %>'      
    }
  };        
  SHERLOCK.videos.initEditForm(settings);  
  
</script>

app/views/videos/_player.html.erb
<div id="video-container-<%= video.id %>"></div>
<script type="text/javascript">
  $(function() {
    var width   = '<%= video.width %>';
    var height  = '<%= video.height.to_i + 20 %>';
    var playerPath = "<%= url_for root_url %>javascript/mediaplayer.swf";
    var s1 = new SWFObject(playerPath,"mediaplayer", width, height,"8");
    s1.addParam("allowfullscreen","false");
    s1.addVariable("width", width);
    s1.addVariable("height", height);
    s1.addVariable("file","<%= file_path('videos', video.flv_path) %>");
    s1.write("video-container-<%= video.id %>");
  });
</script>

app/views/videos/edit.html.erb
<script type="text/javascript" src="/javascript/jquery.jplayer.min.js"></script>

<div class="breadcrumb">
  <%= link_to 'Dashboard', dashboard_path %> /
  <%= link_to 'My Cases', cases_path %> / 
  <%= link_to @case.title, @case %> /
  Edit Video Block  
</div>

<h1>Edit Video Block</h1>

<script type="text/javascript" 
        src="<%= url_for root_url %>javascript/swfobject.js"></script>

<%= render 'form' %>

app/views/videos/new.html.erb
<div class="breadcrumb">
  <%= link_to 'Dashboard', dashboard_path %> /
  <%= link_to 'My Cases', cases_path %> / 
  <%= link_to @case.title, @case %> /
  Create a Video Block
</div>

<h1>Create a Video Block</h1>

<%= render 'form' %>
<%= render 'applet_container' %>

<script type="text/javascript">
  $(function() {
    $('#video_title').focus();
  });
</script>