config/routes.rb
Sherlock::Application.routes.draw do
    
  devise_for :users, :controllers => {
    :sessions       => 'sessions',
    :registrations  => 'registrations'
  }
  
  mount RailsAdmin::Engine => '/admin', :as => 'rails_admin'
  
  resources :text_snippets
  resources :letterheads
  resources :logos
  resources :clients
  
  resources :employees
    
  resources :folders
  resources :reports
  
  resources :contact_messages
  
  resources :block_swaps, :only => [ :create ]  
  
  resources :captured_emails
  
  resources :purchases
  
  resources :subscription_plans
  
  resources :events
  
  resources :file_assets
    
  resources :impersonations  
  
  resources :cases do
    resources :html_details
    resources :data_log_details
    resources :witness_statements
    resources :page_breaks
    resources :pictures
    resources :videos
    resources :invitations
    resources :footers
    resources :notes
    resources :viewers
  end
  
  namespace :dashboard do
    resources :users    
    resources :clients
    resources :blocked_ips
    resources :client_conversions, :only => [:new, :create]
  end
  
  scope '/chargify' do
    get  'subscriptions/new'  => 'chargify/subscriptions#new'
    post 'events/create'      => 'chargify/events#create'
  end  
  
  post 'folders/:id/move_case'      => 'folders#move_case'
  post 'folders/:id/move_out_case'  => 'folders#move_out_case'
    
  resource :account, :only => [:show, :update]
 
  get 'search/index'  => 'search#index', :as => :search
  
  get 'account/upgrade' => 'accounts#upgrade', :as => :upgrade
  get 'account/renew' => 'accounts#renew', :as => :renew
  
  get 'cases/preview/:id' => 'cases#preview', :as => :case_preview
  
  match 'spellcheck/lookup' => 'spellcheck#lookup', 
        :as => :spellcheck, :via => [:get, :post]
  
  post  'temp_videos/exists'  => 'temp_videos#exists', :as => :check_temp_video
  put   'temp_videos'         => 'temp_videos#create', :as => :new_temp_video
  
  get 'dashboard' => 'home#dashboard',  :as => :dashboard
  
  get 'pricing'   => 'home#pricing',    :as => :pricing
  get 'help'      => 'home#help',       :as => :help  
  get 'contact'   => 'home#contact',    :as => :contact
  get 'tos'       => 'home#tos',        :as => :tos
  get 'privacy'   => 'home#privacy',    :as => :privacy
  get 'how_it_works' => 'home#how_it_works', :as => :how_it_works
  
  resources :blocks
  
  get 'logo/:filename' => 'files#logo',
    :constraints => { :filename => /.*/ }, :as => :logo
  
  get 'files/:case_id/:type/:filename' => 'files#show',
    :constraints => { :filename => /.*/ }, :as => :file
  
  get 'video_thumbnails/:case_id/:filename' => 'files#video_thumbnail',
    :constraints => { :filename => /.*/ }, :as => :file_video_thumbnail
  

  root :to => 'home#index'

end

app/views/shared/_account_links.html.erb
<div class="head">
  <%= investigators_only do %>
    <%= disable_if_employee do %>
      <div class="headtxt link-account">
        <%= link_to 'Account', account_path, :title => 'Account Settings' %>
      </div>
    <% end %>
  <% end %>
  <div class="head-account-links">
    <%= investigators_only do %>
      <%= disable_if_employee do %>
        <a class="settings" href="<%= account_path %>" 
           title="Account Settings">Settings</a>
      <% end %>
    <% end %>
    <a class="help" href="<%= help_path %>" title="Help">Help</a>
  </div>
</div>

app/views/shared/_company_name.html.erb
<%  if signed_in? %>
  <h2 id="company-name"><%= current_company.company_name %></h2>
<% end %>

app/views/shared/_flash.html.erb
<div class="flash-messages topbar">  
  <% if flash.present? %>  
    <% flash.each do |key, value| %>
      <div class="msg <%= key %>">
        <%= value %>
      </div>
    <% end %>
  <% end %>
</div>

app/views/shared/_form_errors.html.erb
<% if errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(errors.count, "error") %> found, please correct below:</h2>    
      <ul class="errors-list">
        <% errors.full_messages.each do |msg| %>
          <li><%= msg %></li>
        <% end %>
      </ul>
    </div>

<% end %>

app/views/shared/_java_detect.html.erb
<div class="actions" id="accept-java" style="display:none;">
  <div class="note-accept-prompts">
    <strong>Note:</strong>
    To use <%= func_name %>, please accept any prompts to allow 
    or install the Java plug-in
  </div>
  
  <div class="detecting">
    <div class="detecting-text">Detecting Java version...</div>
    <img class="detecting-spinning" src="/assets/loading_32_140.gif"/>          
    <div id="java-version-result"></div>    
  </div>
  
  <div id="java-applet-launching" style="display:none;">
    <div class="please-wait">
      Starting the app please wait till the red frame appears...
    </div>
    <img class="spinning" src="/assets/loading_32_140.gif"/>
    <div class="app-is-running" 
         style="display:none;"><%= app_name %> launched.</div>
    
  </div>
  <div id="java-install" style="display:none;">       
    Please <strong>
    <span class="upgrade">upgrade</span>
    <span class="install">install</span>
    Java 
    </strong>
    in order to use this feature. Reload this page when done.
    <a title="Free Java Download"           
       href="http://java.com/en/download/index.jsp" 
       class="download_java">Download Java for Free!</a>

  </div>
</div>

app/views/shared/_tinymce.html.erb
<%= javascript_include_tag(root_path + 'tiny_mce/tiny_mce.js') %>

<script type="text/javascript">
var tinyMCEParams = {
  
  mode: 'specific_textareas',
  editor_selector : "rich",
  
  init_instance_callback : SHERLOCK.utils.richEditorInitialized,  

  theme: 'advanced',
  //theme_advanced_statusbar_location : 'top',
  theme_advanced_toolbar_location : 'top',
  plugins : 'spellchecker,table,snippetDropdown',
  spellchecker_rpc_url : "<%= spellcheck_path %>",
  spellchecker_languages : 'English=en',
  content_css: '<%= url_for root_url %>stylesheets/tinymce.css',
  theme_advanced_buttons1: 'undo,redo,|,bold,italic,underline,strikethrough,separator,formatselect,fontselect,fontsizeselect,separator,forecolor,backcolor,separator,spellchecker,separator,justifyleft,justifycenter,justifyright,justifyfull,bullist,numlist,|,snippetDropdown',
  theme_advanced_buttons2: '',
  theme_advanced_buttons3: ''        
}
$(function() {
  if (window.tinyMCECustomInit) {
      tinyMCEParams.setup = function(ed) {
        ed.onInit.add(window.tinyMCECustomInit);
      };
  }          
  tinyMCE.init(tinyMCEParams);    
});
</script>

app/views/shared/_top_user_links.html.erb
<div id="top-user-links">
  <div class="links-list">
  <% if signed_in? %>     
    <%= investigators_only do %>
      <%= render 'letterhead_link' %> |   
      <%= link_to 'Text Snippets', text_snippets_path %> |
    <% end %>
    <%= link_to 'My Cases', cases_path %> |    
    <%= investigators_only do %>
      <%= link_to 'Clients', clients_path %> |
      <%= disable_if_employee do %>
        <%= link_to 'Employees', employees_path %> |
      <% end %>
    <% end %>
    <%- if current_user.admin? %>
      <%= link_to 'Admin area', '/admin' %> |
    <%- end %>
    <%= link_to 'Logout', destroy_user_session_path, :method => :delete %>      
  <% else %>    
    <%= link_to signup_link_label, new_user_registration_path %>
  <% end %>
  </div>
  <% if signed_in? %>
    <%= render 'shared/account_links' %>
  <% end %>
</div>