config/routes.rb
Sherlock::Application.routes.draw do
    
  devise_for :users, :controllers => {
    :sessions       => 'sessions',
    :registrations  => 'registrations'
  }
  
  mount RailsAdmin::Engine => '/admin', :as => 'rails_admin'
  
  resources :text_snippets
  resources :letterheads
  resources :logos
  resources :clients
  
  resources :employees
    
  resources :folders
  resources :reports
  
  resources :contact_messages
  
  resources :block_swaps, :only => [ :create ]  
  
  resources :captured_emails
  
  resources :purchases
  
  resources :subscription_plans
  
  resources :events
  
  resources :file_assets
    
  resources :impersonations  
  
  resources :cases do
    resources :html_details
    resources :data_log_details
    resources :witness_statements
    resources :page_breaks
    resources :pictures
    resources :videos
    resources :invitations
    resources :footers
    resources :notes
    resources :viewers
  end
  
  namespace :dashboard do
    resources :users    
    resources :clients
    resources :blocked_ips
    resources :client_conversions, :only => [:new, :create]
  end
  
  scope '/chargify' do
    get  'subscriptions/new'  => 'chargify/subscriptions#new'
    post 'events/create'      => 'chargify/events#create'
  end  
  
  post 'folders/:id/move_case'      => 'folders#move_case'
  post 'folders/:id/move_out_case'  => 'folders#move_out_case'
    
  resource :account, :only => [:show, :update]
 
  get 'search/index'  => 'search#index', :as => :search
  
  get 'account/upgrade' => 'accounts#upgrade', :as => :upgrade
  get 'account/renew' => 'accounts#renew', :as => :renew
  
  get 'cases/preview/:id' => 'cases#preview', :as => :case_preview
  
  match 'spellcheck/lookup' => 'spellcheck#lookup', 
        :as => :spellcheck, :via => [:get, :post]
  
  post  'temp_videos/exists'  => 'temp_videos#exists', :as => :check_temp_video
  put   'temp_videos'         => 'temp_videos#create', :as => :new_temp_video
  
  get 'dashboard' => 'home#dashboard',  :as => :dashboard
  
  get 'pricing'   => 'home#pricing',    :as => :pricing
  get 'help'      => 'home#help',       :as => :help  
  get 'contact'   => 'home#contact',    :as => :contact
  get 'tos'       => 'home#tos',        :as => :tos
  get 'privacy'   => 'home#privacy',    :as => :privacy
  get 'how_it_works' => 'home#how_it_works', :as => :how_it_works
  
  resources :blocks
  
  get 'logo/:filename' => 'files#logo',
    :constraints => { :filename => /.*/ }, :as => :logo
  
  get 'files/:case_id/:type/:filename' => 'files#show',
    :constraints => { :filename => /.*/ }, :as => :file
  
  get 'video_thumbnails/:case_id/:filename' => 'files#video_thumbnail',
    :constraints => { :filename => /.*/ }, :as => :file_video_thumbnail
  

  root :to => 'home#index'

end

app/models/picture.rb
class Picture < ActiveRecord::Base
  
  include BlockDetail  
  include PictureAsset
  
  # at some point we will remove it:
  include FileAssetUtils
      
  belongs_to :block  
  belongs_to :storage
  
  has_many :file_assets, :foreign_key => 'parent_id', 
           :conditions => "parent_type = 'pictures'", 
           :dependent => :destroy
  
  validates :title, :presence => true
  
  validate :require_upload_for_a_new_image, :unless => :persisted?
  validate :accept_only_image_uploads, :if => :has_uploaded_file?
  
  attr_accessor :uploaded_file
  
  attr_accessible :title, :uploaded_file, :alignment, :scaling, :unique_code
    
  before_save :process_upload, :if => :has_uploaded_file?  
  
  before_destroy :delete_files  
  
  after_save :invalidate_report  
  after_save :generate_file_assets, :if => :has_uploaded_file?
  
  def self.generate(block)
    Picture.new do |p|
      p.block = block
      p.unique_code = generate_unique_code
    end        
  end
          
  def generate_file_assets
    if self.file_assets.empty?     
      generate_main_asset
      generate_orig_asset if File.exists?(orig_path)
      generate_backup_asset if File.exists?(backup_path)        
    end
  end
    
  #
  # return path from the 'main' file asset
  #
  #def path
  #  main_file_asset.path
  #end    
  
  def online_dims
    
    max_width = Report::MAX_PAGE_WIDTH
    min_width = 450
    
    dims = dimensions
    
    return dims if (dims == [0, 0]) || (dims[0] <= max_width)
            
    result = Picture.scale_to_bounds([dims[0], dims[1]], [max_width, 0])
    ratio = (0.0 + result[1]) / result[0]
    if result[0] < min_width
      result[0] = min_width
      result[1] = (ratio * result[0]).round
    end
    result
  end
  
  def self.scale_to_bounds(dims, max_dims)

    return max_dims if dims.nil? || dims[0].nil? || dims[1].nil?
    
    ratio = (0.0 + dims[0]) / dims[1]
    
    if (dims[0] > max_dims[0])
      dims[0] = max_dims[0]
      dims[1] = dims[0] / ratio
    end
    
    if (dims[1] > max_dims[1]) && (max_dims[1] > 0)
      dims[1] = max_dims[1]
      dims[0] = dims[1] * ratio
    end
    
    [ dims[0].round, dims[1].round ]
    
  end
  
  def file_type
    'pictures'
  end
      
  def backup
    FileUtils.copy_file(full_filepath, backup_path)
    generate_backup_asset
  end
  
  def backup_path    
    full_filepath + '.bak'
  end
  
  def remove_backup
    File.delete(backup_path) if File.exists?(backup_path)
  end
  
  def restore_from_backup    
    File.rename(backup_path, full_filepath)    
    update_dims_and_save
    backup_file_asset.destroy if backup_file_asset
  end
    
  def crop(rectangle)   
    
    cropped = false
    
    x, y, w, h = rectangle
    
    cropper = Cropper.new
    result = cropper.crop(full_filepath, x, y, w, h)    
    
    # sanity check - the result must exist and its dimensions have to match
    # the desired ones:    
    if result.present? && File.exists?(result)
        if Dimensions.dimensions(result) == [w.to_i, h.to_i]          
          backup          
          File.rename(result, full_filepath)                      
          update_dims_and_save
          update_filesize File.size(full_filepath)
          cropped = true
        end      
    end        
    cropped    
  end
  
  def move_to_storage(storage)    
    file_assets.each { |asset| asset.move_to_storage storage }
    self.storage = storage
    self.save
  end
  
  #
  # Fix the broken main file asset (empty path, content_type and size)
  #
  def fix_main_file_asset
    asset = main_file_asset
    if path.present? && asset && asset.path.to_s.empty?
      filepath = File.join(base_dir, path)
      if File.exists?(filepath)
        asset.path = path
        asset.content_type = content_type if content_type == 'image/png'        
        asset.filesize = File.size(filepath)
        asset.save
      end      
    end
  end
  
  def update_filesize(size)
    asset = main_file_asset
    asset.filesize = size
    asset.save
  end
    
  def width_for_preview
    width_for_display Report::MAX_PAGE_WIDTH
  end
  
  def width_for_display(max_width)    
    dims = dimensions
    dims ? (dims[0] > max_width ? max_width : dims[0]) : 0
  end
    
  def delete_files
    if self.file_assets.empty?
      delete_file
      remove_backup
      remove_original_file   
    else
      file_assets.destroy_all
    end
  end

  def self.populate_missing_codes
    Picture.where(:unique_code => nil).each do |pic|
      pic.unique_code = Picture.generate_unique_code
      pic.save
    end
    Picture.where(:unique_code => '').each do |pic|
      pic.unique_code = Picture.generate_unique_code
      pic.save
    end
  end
  
  def as_json(options = {}) 
    
    options[:except] ||= []
    
    options[:except] += [:original_filename, :content_type]
    result = super(options)
        
    result['caption'] = result['title']
    
    if options[:for_pdf]
      result['path'] = main_file_asset.full_filepath
    end
    
    dims = dimensions
    result['width'] = dims[0]
    result['height'] = dims[1]
    
    result
  end
  
  def self.generate_unique_code
    len = 10
    code = ''
    until code.present? && (!Picture.find_by_unique_code(code))
      code = generate_random_code(len)
    end
    code    
  end
  
  private    
    
  def self.generate_random_code(len)
    (0...len).map{ ('a'..'z').to_a[rand(26)] }.join
  end           
  
end

app/controllers/pictures_controller.rb
class PicturesController < ApplicationController
  
  before_filter :authenticate_user!
  before_filter :authorize_pi!
  
  #
  # Note: we may want to remove it, if this controller will also be
  #       used to upload pictures unlinked with any blocks/cases
  #
  before_filter :resolve_case, :only => [ :new, :edit, :show, :update, :create ]
  
  before_filter :verify_case_author!, :only => [ :new, :edit, :update, :create ]
  
  def new
    
    block = Block.new
    block.case = @case
    @picture  = Picture.generate(block)
    
    @insert_before_id = params[:insert_before_id].to_i    
    @cookie = cookies['_sherlock_session']
    
  end
  
  def create
    
    params[:picture][:user] = current_company     
    
    image = params[:upload] ? params[:upload]['image'] : nil    
    params[:picture][:uploaded_file] = image if image    
        
    @picture = Picture.new(params[:picture])
    block = Block.new(:case => @case)    
    @insert_before_id = params[:insert_before_id].to_i
    block.insert_before_id = @insert_before_id    
    @picture.block = block          
        
    respond_to do |format|
      if (@picture.save) 
        format.html { redirect_to(@case, :notice => 'Picture block has been added') }
      else        
        format.html do
          flash[:alert] = 'Picture could not be saved'
          render :action => 'new'           
        end
      end
    end        
    
  end
  
  def edit
    @insert_before_id = 0
    @picture = @case.pictures.find_by_id(params[:id])
    @cookie = cookies['_sherlock_session']
    redirect_to cases_path unless @picture
    
  end
  
  def show
    @picture = @case.pictures.find_by_unique_code(params[:id])
    respond_to do |format|
      format.js { render :json => @picture }
    end
  end
  
  def update
    
    @picture = @case.pictures.find_by_id(params[:id])    
    redirect_to cases_path unless @picture
    
    params[:upload] ||= {}
    image = params[:upload]['image']
    
    params.delete(:crop) if params[:crop] == ["", "", "", ""]
    
    logger.debug 'Params crop:'
    logger.debug params[:crop]
    
    if params[:crop]
      if (params[:crop_new_block].to_i == 1)
        @case.create_block_from_picture(@picture, params[:crop])
      else
        @picture.crop(params[:crop])
      end
    end
    
    respond_to do |format|      
      params[:picture][:uploaded_file] = image if image      
      if @picture.update_attributes(params[:picture])
        format.html { redirect_to @case, 
                      :notice => 'The block has been successfully updated' }                
      else
        format.html do 
          flash[:alert] = 'The block has not been updated'
          render :action => 'edit'          
        end
      end
    end
    
  end
  
  private
    
  def resolve_case
    resolve_case_using_param(:case_id)
  end
  
  def verify_case_author!    
    is_author = (@case.author == current_company)
    redirect_to @case unless is_author    
  end
  
end

app/helpers/picture_helper.rb
module PictureHelper
  
  def file_picture_path(picture)
    file_path(picture.block.case_id, 'pictures', picture.path)
  end
  
  def image_alignment_options
    [
      ['None', nil],
      ['Left', 'left'],
      ['Right', 'right'],
      ['Center', 'center']
    ]
  end
  
  def image_scaling_options
    [
      ['None', nil],
      ['50%', '50']      
    ]
  end
  
  def picture_dynamic_style(picture)
    
    online_width = picture.online_dims[0]
    style = "width:#{online_width}px;"
    is_narrow_elt = online_width <= Report::NARROW_ELT_WIDTH
    
    case picture.alignment
    when 'left'
      if is_narrow_elt
        style += 'float:left;margin:0 1em 1em 0'
      else
        style += 'clear:both;'
      end
    when 'right'
      if is_narrow_elt
        style += 'float:right;margin:0 0em 1em 1em'
      else
        style += 'clear:both;'
      end
    when 'center'
      style += 'text-align:center;clear:both;margin-top:1em;'
    else
      style += 'clear:both;margin-top:1em;'
    end
    
    style
    
  end
  
  def image_logo_tag_constrained(logo, max_dims)
    dims = Picture.scale_to_bounds(logo.dims, max_dims)
    link = logo_path(logo.path)
    size_string = dims[0].floor.to_s + 'x' + dims[1].floor.to_s    
    title = logo.dims ?  "Original Dimensions: #{logo.dims[0]}x#{logo.dims[1]}" : ""    
    link_to(image_tag(url_for(link), :size => size_string, :title => title), 
            link, :target => '_blank')
  end
    
end

app/views/pictures/_applet_container.html.erb
<div id="appletContainer" style="display:none;height:60px;"></div>

<script type="text/javascript">      
    $(function() {            
      var data = {
        picture_id : <%= @picture.id.to_i %>,
        updated_at : '<%= @picture.updated_at %>',
        unique_code: '<%=  @picture.unique_code %>',
        cookie: '<%= @cookie %>',
        insert_before_id: '<%= @insert_before_id %>',
        urls : {
          root : '<%= root_url %>',
          base_redirect: '<%= case_pictures_path(@case) %>',
          check: '<%= case_picture_path(@case, @picture.unique_code, :js) %>',
          post: '<%= @picture.id ? case_picture_url(@case, @picture) : case_pictures_url(@case) %>'
        }
      }            
      SHERLOCK.pictures.initAppletContainer(data);                     
    });        
</script>

app/views/pictures/_form.html.erb
<%= render 'shared/form_errors', :errors => @picture.errors %>

<%= form_for([@case, @picture], 
    :html => { :enctype => 'multipart/form-data' }) do |f| %>

<input type="hidden" name="insert_before_id" 
       value="<%= @insert_before_id %>"/>

<div class="field">  
  <%= f.label :title, 'Title :' %>  
  <div class="boxfield">
    <%= f.text_field :title, :class => 'txtfield txtfield-wide', :size => 100 %>
  </div>
</div>

<div class="field">
  <%= f.label :alignment, 'Alignment :' %>  
  <div class="rich-dropdown-wrapper rich-dropdown-wrapper-x">
    <%= f.select :alignment, image_alignment_options %>
  </div>
</div>

<div class="field">
  <%= f.label :scaling, 'Scaling (report) :' %>  
  <div class="rich-dropdown-wrapper rich-dropdown-wrapper-x">
    <%= f.select :scaling, image_scaling_options %>
  </div>
</div>

  <%= f.hidden_field :unique_code unless @picture.id %>

  <% if @picture.id %>
    <div class="field-right" style="margin-bottom:1em;">
      <div style="margin: 1em 0 0 0;clear:both;padding-top: 1em;">    
        <img 
          id="picture-holder"
          style="border: 1px solid black;"
          width="<%= @picture.width_for_display(750) %>"
          src="<%= file_picture_path(@picture) %>"/>    
      </div>            
      
      <a href="#"
         id="btn-change-picture">Change the Picture</a>
                      
      <a href="#" 
         style="visibility:hidden;"
         id="link-keep-picture">Keep the picture</a>
      
      <input type="hidden" name="crop_new_block" value=""/>
         
      <input type="hidden" id="crop-x" name="crop[]"/>
      <input type="hidden" id="crop-y" name="crop[]"/>
      <input type="hidden" id="crop-w" name="crop[]"/>
      <input type="hidden" id="crop-h" name="crop[]"/>             
      
      <%= stylesheet_link_tag root_path + 'stylesheets/jquery.jcrop.min.css' %>      
      <%= javascript_include_tag root_path + 'javascript/jquery.jcrop.min.js' %>
      
      <script type="text/javascript">      
      $(function() {
        SHERLOCK.pictures.initForm();
      });        
      </script>         
    </div>
    <div id="image-field-wrapper" style="display:none;">
  <% end %>

    <div class="field" style="margin-bottom:5px;">
      <label for="upload_image">Select Image :</label>      
      <span class="btn2 fileinput-button">
      <%= file_field 'upload', 'image', 
          :title => 'Select image file to be uploaded' %>                      
          <span>Browse...</span>
      </span>
      <strong>OR &nbsp;&nbsp;</strong>        
        <button id="btn-screen-capture"                
                type="button" class="button2 button2-wide btn-picture-capture">
          <div>
            Screen Capture
          </div>
        </button>
          
    </div>
      
    <%= render 'shared/java_detect', 
        :func_name => 'screen capture', :app_name => 'Frame capture launched' %>   
      
  <% if @picture.id %>
    </div>
  <% end %>
      
<div class="actions" style="padding-top:0em;">
  <%= f.submit 'Save', :class => :button %>
  <% if @picture.id %>
    <%= link_to 'Cancel', @case %>
  <% end %>  
</div>

<% end %>

app/views/pictures/edit.html.erb
<div class="breadcrumb">
  <%= link_to 'Dashboard', dashboard_path %> /
  <%= link_to 'My Cases', cases_path %> / 
  <%= link_to @case.title, @case %> /
  Edit Picture Block
</div>

<h1>Edit Picture Block</h1>

<%= render 'form' %>
<%= render 'applet_container' %>

<div id="dialog-crop-confirm" title="Confirm the picture crop">
  <p style="margin: 1em 0 0 0;">
    
    <span class="ui-icon ui-icon-alert" 
          style="float:left; margin:0 7px 20px 0;"></span>
    Do you want <strong>REPLACE</strong> the existing picture with contents 
    of the cropped area, or <strong>CREATE</strong> a new picture?
  </p>
</div>

<script type="text/javascript">
  $(function() {
    SHERLOCK.pictures.initEditForm();
    $('#picture_title').focus();
  });
</script>

app/views/pictures/new.html.erb
<div class="breadcrumb">
  <%= link_to 'Dashboard', dashboard_path %> /
  <%= link_to 'My Cases', cases_path %> / 
  <%= link_to @case.title, @case %> /
  Create a Picture Block
</div>

<h1>Create a Picture Block</h1>

<%= render 'form' %>
<%= render 'applet_container' %>

<script type="text/javascript">
  $(function() {
    $('#picture_title').focus();
  });
</script>